# Generated by Django 4.1.4 on 2022-12-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comment_comment_alter_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
    ]
