# Generated by Django 4.1.4 on 2022-12-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_user_comment_user_alter_bid_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auction',
            new_name='item',
        ),
        migrations.CreateModel(
            name='ClosedAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_auction', to='auctions.listing')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to='auctions.bid')),
            ],
        ),
    ]
