# Generated by Django 4.1.4 on 2022-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_auction_comment_item_closedauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
