# Generated by Django 4.1.4 on 2022-12-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_closedauction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedauction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to='auctions.bid'),
        ),
    ]
